#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d     

bspc config border_width         1
bspc config window_gap           1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config normal_border_color '#5b5b5b'
bspc config focused_border_color '#ffffff'

bspc rule -a Gimp state=floating follow=on
bspc rule -a Qalculate-gtk \
	state=floating sticky=off follow=off focus=on \
	rectangle=640x360
bspc rule -a '*:*:Picture-in-Picture' locked=on state=floating follow=off sticky=on rectangle=426x240+0+838 focus=off
bspc rule -a Steam desktop='^5' follow=off focus=off
bspc rule -a "Heroic Games Launcher" desktop='^5' follow=off focus=off
bspc rule -a qBittorrent -o desktop='^4' state=tiled

## Always Floating Apps
declare -a floating=(Thunar Onboard Yad 'Firefox:Places' \
Viewnior feh Nm-connection-editor)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done

~/.fehbg &
picom -f &
killall xcape
xcape -e 'Super_L=Alt_L|F2'
dunst &
#qbittorrent &
