#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d     

bspc config border_width         1
bspc config window_gap           1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config normal_border_color '#5b5b5b'
bspc config focused_border_color '#ffffff'

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

## Always Floating Apps
declare -a floating=(alacritty-float Pcmanfm Thunar Onboard Yad 'Firefox:Places' \
Viewnior feh Nm-connection-editor)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done


~/.fehbg &
picom -f &
polybar qbar &
